---
- hosts: bifrost 
  remote_user: root
  handlers:
    - name: run /sbin/reboot
      listen: reboot machine
      command: /sbin/reboot

    - name: wait for sshd
      listen: reboot machine
      local_action: wait_for host={{inventory_hostname}} search_regex=OpenSSH port=22 timeout=300
  
  tasks:
    - name: add necessary packages
      package: pkg={{ item }} state=present
      with_items:
        - openvpn
        - iptables-services
        - python-pyotp
        - python2-future
        - python-ldap
        - sqlite
        - python-qrcode

    - name: copy iptables config
      template: src=files/etc/sysconfig/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=u+rw,g+r,o+r

    - name: enable iptables
      service: name=iptables state=started enabled=yes

    - name: enable ip_forward
      copy: src=files/etc/sysctl.d/90-ip_forward.conf dest=/etc/sysctl.d/90-ip_forward.conf owner=root group=root mode=u+rw,g+r,o+r

    - name: copy OpenVPN config file
      template: src=files/etc/openvpn/server/main.conf dest=/etc/openvpn/server/main.conf owner=root group=root mode=u+rw,g+r,o+r

    - name: create opt directory
      file: state=directory path=/opt/{{ item }} owner=root group=root mode=u+rwx,g+rx,o+rx
      with_items:
        - bifrost
        - bifrost/bin
        - bifrost/etc
        - bifrost/sbin
        - bifrost/var
        - bifrost/var/log
        - bifrost/mails

    - name: create var directory
      file: state=directory path=/var/run/openvpn owner=root group=root mode=u+rwx,g-rwx,o-rwx

    - name: copy script files
      copy: src=files/bin/{{ item }} dest=/opt/bifrost/bin/{{ item }} owner=root group=root mode=u+rwx,g+rx,o+rx
      with_items:
        - ovpn-auth-user-pass-verify.py
        - ovpn-tls-verify.py
        - ovpn-client-logger.py

    - name: copy .ovpn template
      template: src=files/opt/bifrost/etc/template.ovpn dest=/opt/bifrost/etc/template.ovpn owner=root group=root mode=u+rw,g+r,o+r

    - name: copy certificate files
      copy: src=tmp/{{item}} dest=/opt/bifrost/etc/{{item}} owner=root group=root mode=u+rw,g-rwx,o-rwx
      with_items:
        - ca.crt
        - ca.key
        - openvpn-server.crt
        - openvpn-server.key
        - openvpn-server-pw.txt
        - dh-4096.pem
        - tls-auth.pem
        - heimdall-server.crt
        - heimdall-server.key
        - heimdall-client.crt
        - heimdall-client.key
        - bifrost-server.crt
        - bifrost-server.key

    - name: copy Gjallarhorn email templates
      copy: src=../mails/{{item}} dest=/opt/bifrost/mails/{{item}} owner=root group=root mode=u+rw,g+r,o+r
      with_items:
        - month.tmpl
        - week.tmpl
        - day.tmpl

    - name: copy server binaries
      copy: src=tmp/{{item}} dest=/opt/bifrost/sbin/{{item}} owner=root group=root mode=u+rwx,g+rx,o+rx
      with_items:
        - bifrost
        - heimdall
        - gjallarhorn
        - pgcert
    
    - name: copy server config files
      template: src=../etc/config-{{item}}-example.json dest=/opt/bifrost/etc/{{item}}.json owner=root group=root mode=u+rw,g-rwx,o-rwx
      with_items:
        - bifrost
        - heimdall
        - gjallarhorn
    
    - name: copy systemd service files
      copy: src=files/etc/{{item}} dest=/lib/systemd/system/{{item}} owner=root group=root mode=u+rw,g+r,o+r
      with_items:
        - bifrost.service
        - heimdall.service

    - name: enable systemd services
      service: name={{item}} state=started enabled=yes
      with_items:
        - bifrost
        - heimdall
    
    - name: copy web app UI static files
      copy: src=../static/ dest=/opt/bifrost/static

    - name: create sqlite DB
      command: /usr/bin/sqlite3
      args:
        stdin:
          .open /opt/bifrost/heimdall.sqlite3

          CREATE TABLE certs (rowid integer primary key, email text not null, fingerprint text not null unique, desc text, created timestamp not null default current_timestamp, expires timestamp not null, revoked timestamp default null);
          CREATE INDEX certs_email_idx on certs (email);
          CREATE INDEX certs_fp_idx on certs (fingerprint);
          CREATE INDEX certs_created_idx on certs (created);
          CREATE INDEX certs_revoked_idx on certs (revoked);

          CREATE TABLE totp (rowid integer primary key, email text not null unique, seed text not null, created timestamp not null default current_timestamp, updated timestamp not null default current_timestamp);
          CREATE INDEX totp_email_idx on totp (email);

          CREATE TABLE events (rowid integer primary key, event text not null, email text not null, value text not null, ts timestamp not null default current_timestamp);
          CREATE INDEX events_evt_idx on events (event);
          CREATE INDEX events_email_idx on events (email);
          CREATE INDEX events_value_idx on events (value);
          CREATE INDEX events_ts_idx on events (ts);

          CREATE TABLE settings (rowid integer primary key, key text not null unique, value text not null, modified timestamp not null default current_timestamp);
          CREATE INDEX settings_key_idx on settings (key);
          CREATE INDEX settings_mod_idx on settings (modified);

          CREATE TABLE whitelist (rowid integer primary key, email text not null unique, modified timestamp not null default current_timestamp);
          CREATE INDEX whitelist_email_idx on settings (key);
          CREATE INDEX whitelist_mod_idx on settings (modified);
        creates: /opt/bifrost/heimdall.sqlite3
